force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <label>Event Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Event Attendee</relationshipLabel>
    <relationshipName>Event_Attendee</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Attendee</relationshipLabel>
    <relationshipName>Event_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event - Speaker</label>
    <nameField>
        <label>Event - Speaker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event - Speaker</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event - Speaker</relationshipLabel>
    <relationshipName>Event_Speaker</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Speaker__c/fields/Speaker__c.field-meta.xml
<CustomField>
    <fullName>Speaker__c</fullName>
    <label>Speaker</label>
    <referenceTo>Speaker__c</referenceTo>
    <relationshipLabel>Event - Speaker</relationshipLabel>
    <relationshipName>Event_Speaker</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>g</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Location__c/fields/Land_Mark__c.field-meta.xml
<CustomField>
    <fullName>Land_Mark__c</fullName>
    <label>Land Mark</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Location__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Street</label>
    <length>256</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EventSpeakerController.cls
public with sharing class EventSpeakerController {
        
    
    @AuraEnabled(cacheable=true)
    public static List<Speaker__c> getEventSpeakerById(id eventSpeakerId) {
       
             Set<Id> speakersId = new Set<Id>();
 
        
            for (Event_Speaker__c event_speaker : [
                SELECT Id, Speaker__r.id 
                FROM Event_Speaker__c
                WHERE Event__r.id =: eventSpeakerId   
            ]) {
            
                speakersId.add(event_speaker.Speaker__r.id);
                System.debug(speakersId);
            }

            List<Speaker__c> speakers =  [
                SELECT Id, Name, Email__c, Phone__c,Company__c
                FROM Speaker__c
                WHERE Id IN : speakersId];
       
         System.debug(speakers);
         return speakers;
    }
       

        @AuraEnabled(cacheable=true)
        public static  List<Location__c> getLocationDetails(string eventId) {
            
            Set<Id> locationId = new Set<Id>();

            System.debug(eventId);
            for (Event__c event : [
                SELECT Id, Location__r.id
                FROM Event__c
                WHERE id = : eventId    
            ]) {
            
                locationId.add(event.location__r.id);
                System.debug(locationId);
            }

    
           List<Location__c> location =  [
             SELECT Id, City__c, Country__c, Land_Mark__c, Postal_Code__c, State__c,Street__c,Verified__c
             FROM Location__c
             WHERE id IN :locationId
             ];

             System.debug(location);
             //System.debug(test);
             return location;
                
    }

     @AuraEnabled(cacheable=true)
     public static List<Attendee__c> getAttendeesDetails(id eventAtteendeeId) {
        
              Set<Id> attendeeId = new Set<Id>();
  
         
             for (Event_Attendee__c event_attendee : [
                 SELECT Id, Attendee__r.id
                 FROM Event_Attendee__c
                 WHERE Event__r.id =: eventAtteendeeId   
             ]) {
             
                attendeeId.add(event_attendee.Attendee__r.id);
                 System.debug(attendeeId);
             }
 
             List<Attendee__c> attendee =  [
                 SELECT Id, Name, Email__c, Phone__c, Company_Name__c,Location__c
                 FROM Attendee__c
                 WHERE Id IN : attendeeId];
        
          System.debug(attendee);
          return attendee;
    }
        

}



     /**     List<Speaker__c> test =  [
            SELECT Id, Name ,(SELECT id, Speaker__c FROM Event_Speaker__r  WHERE Event__c =: eventSpeakerId)
            FROM Speaker__c
            
             List<Speaker__c> speakers =  [
            SELECT Id, Name ,(SELECT id, Speaker__c FROM Event_Speaker__r  WHERE Event__c =: eventSpeakerId)
            FROM Speaker__c];
       ]; */


//a007S0000031DFvQAM