force-app/main/default/objects/Attendee__c/Attendee__c.object-meta.xml
<CustomObject>
    <label>Attendee</label>
    <nameField>
        <label>Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attendees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/People_Attending__c.field-meta.xml
<CustomField>
    <fullName>People_Attending__c</fullName>
    <label>People Attending</label>
    <summaryForeignKey>Event_Attendee__c.Event__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/Event_Attendee__c.object-meta.xml
<CustomObject>
    <label>Event Attendee</label>
    <nameField>
        <label>Event Attendee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Attendee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Attendee__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <label>Attendee</label>
    <referenceTo>Attendee__c</referenceTo>
    <relationshipLabel>Event Attendee</relationshipLabel>
    <relationshipName>Event_Attendee</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Event Attendee</relationshipLabel>
    <relationshipName>Event_Attendee</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Location</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeEventsController.cls
public with sharing class AttendeeEventsController {
    @AuraEnabled(cacheable=true)
    
    public static list<Event__c> getEventListUpComming(String attendeeId) {
        
        Set<Id> eventId = new Set<Id>();

        for (Event_Attendee__c event_attendee : [
                 SELECT Id, Event__r.id
                 FROM Event_Attendee__c
                 WHERE Attendee__r.id =: attendeeId 
             ]) {
             
                eventId.add(event_attendee.Event__r.id);
                 System.debug(attendeeId);
             }

             List<Event__c> events =  [
                SELECT id,Name,Location__c,Start_DateTime__c,End_DateTime__c,People_Attending__c
                FROM Event__c
                WHERE Id IN : eventId AND Start_DateTime__c > TODAY];

                return events;

        
    }
    @AuraEnabled(cacheable=true)
    public static list<Event__c> getEventListRelated(String attendeeId) {
        
        Set<Id> eventId = new Set<Id>();

        for (Event_Attendee__c event_attendee : [
                 SELECT Id, Event__r.id
                 FROM Event_Attendee__c
                 WHERE Attendee__r.id =: attendeeId 
             ]) {
             
                eventId.add(event_attendee.Event__r.id);
                 System.debug(attendeeId);
             }

             List<Event__c> events =  [
                SELECT id,Name,Location__c,Start_DateTime__c,End_DateTime__c,People_Attending__c
                FROM Event__c
                WHERE Id IN : eventId AND End_DateTime__c < TODAY];

                return events;

        
    }
}